# Generated by Django 4.0.4 on 2022-05-05 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Serial number of the drone', max_length=100, unique=True)),
                ('model', models.CharField(choices=[('LW', 'Lightweight'), ('MW', 'Middleweight'), ('CW', 'Cruiserweight'), ('HW', 'Heavyweight')], default='LW', help_text='Model of the drone', max_length=13)),
                ('weight_limit', models.DecimalField(decimal_places=2, help_text='Weight limit possible to carry. The max value is 500gr', max_digits=5, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('battery_capacity', models.IntegerField(default=100, help_text="Current percent of battery's capacity", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('IE', 'IDLE'), ('LG', 'LOADING'), ('LD', 'LOADED'), ('DG', 'DELIVERING'), ('DD', 'DELIVERED'), ('RG', 'RETURNING')], default='IE', help_text='State of the drone', max_length=10)),
            ],
        ),
    ]
