# Generated by Django 4.0.4 on 2022-05-13 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='Serial number of the drone', max_length=100, unique=True)),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', help_text='Model of the drone', max_length=13)),
                ('weight_limit', models.DecimalField(decimal_places=2, help_text='Weight limit possible to carry. The max value is 500 grams.', max_digits=5, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('battery_capacity', models.IntegerField(default=100, help_text="Current percent of battery's capacity. From 0% to 100%.", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', help_text='State of the drone', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Allowed only letters, numbers, ‘-‘, ‘_’.')])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the medication in grams', max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(help_text='Code of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Allowed only upper case letters, underscore and numbers.')])),
                ('image', models.ImageField(help_text='Image of the medication', null=True, upload_to='images_med')),
            ],
        ),
        migrations.CreateModel(
            name='LoadInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Amount of medications that is loaded', validators=[django.core.validators.MinValueValidator(1)])),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_app.drone')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_app.medication')),
            ],
        ),
    ]
