# Generated by Django 4.0.4 on 2022-05-05 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9-_]+', 'Allowed only letters, numbers, ‘-‘, ‘_’.')])),
                ('weight', models.IntegerField(help_text='Weight of the medication in grams', validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(help_text='Code of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('[A-Z0-9_]+', 'Allowed only upper case letters, underscore and numbers.')])),
                ('image', models.ImageField(help_text='Image of the medication', upload_to='images_med')),
            ],
        ),
    ]
