# Generated by Django 4.0.4 on 2022-05-05 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0002_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(null=True, to='drone_app.medication'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='battery_capacity',
            field=models.IntegerField(default=100, help_text="Current percent of battery's capacity. From 0% to 100%.", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.DecimalField(decimal_places=2, help_text='Weight limit possible to carry. The max value is 500 grams.', max_digits=5, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)]),
        ),
    ]
