# Generated by Django 4.0.4 on 2022-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0003_drone_medications_alter_drone_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(to='drone_app.medication'),
        ),
    ]
