# Generated by Django 4.0.4 on 2022-05-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0004_alter_drone_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='drones', to='drone_app.medication'),
        ),
    ]
