# Generated by Django 4.0.4 on 2022-05-08 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0005_alter_drone_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], default='Lightweight', help_text='Model of the drone', max_length=13),
        ),
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', help_text='State of the drone', max_length=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(help_text='Code of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Allowed only upper case letters, underscore and numbers.')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(help_text='Image of the medication', null=True, upload_to='images_med'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Name of the medication', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Allowed only letters, numbers, ‘-‘, ‘_’.')]),
        ),
    ]
